# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

secret_key_base: ""
web_protocol: "http"
web_fqdn: "lvh.me:3000"
app_db_host: ""
app_db_port: ""
app_db_user: ""
app_db_password: ""
app_db_pool: ""
mail_host: ""
mail_port: ""
mail_user: ""
mail_password: ""
bugsnag_rails_token: ""
skylight_token: ""
mixpanel_token: ""
devise_jwt_secret_key: <%= "0defb5b2e4420f183fdfc2ce805c570368fa42f235410dc2bc58b346a1562d94812c77b252d27f0bc27a648931"\
                         "e7a091965414d4d5b8e33bfd91f42243d81d3f" %>
client_dev_port: "3000"